# ==========================================
# 1. APPLICATION CONFIGURATION
# ==========================================
spring.application.name=ApplyFlow
spring.profiles.active=@activatedProperties@
# ==========================================
# 2. LOCAL POSTGRESQL DATABASE CONNECTION
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/tracker_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# 3. GOOGLE OAUTH2 CLIENT CONFIGURATION
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile,https://www.googleapis.com/auth/gmail.send

# Tell Google to hand over a persistent refresh token for background tasks
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth