# aplication-dev.properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tracker_db}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
app.api.base-url=http://localhost:8080
app.frontend-url=http://localhost:4200/stats
app.cors.allowed-origins=http://localhost:4200
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=false
